runtime: python27
api_version: 1
# application: lets-make-a-website
threadsafe: true
service: default
handlers:
- url: /.*
  script: app.app
skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*\.rst$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- docs/(.*)
- fonts/(.*)
- js/(.*)
- less/(.*)
